version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "	34:52:7e:df:1c:2b:b6:52:44:c1:bf:63:da:a4:a9:83"
      - checkout
      - run:
          name: Set NODE_NO_WARNINGS variable
          command: export NODE_NO_WARNINGS=1
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t nicolaszelarayan/portfolio:$CIRCLE_SHA1 .
      - run: docker push nicolaszelarayan/portfolio:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no -t -t usuario@34.28.124.108 "sudo docker stop portfolio || true"
      - run: ssh -o StrictHostKeyChecking=no -t -t usuario@34.28.124.108 "docker rm portfolio || true"
      - run: ssh -o StrictHostKeyChecking=no -t -t usuario@34.28.124.108 "docker run -p 8090:5173 -d --name portfolio nicolaszelarayan/portfolio:$CIRCLE_SHA1"